{
 "title": "smarthome - [15', 24h]",
 "time": { "from": "2023-01-18T22:00:00.000Z", "to": "2023-01-19T21:59:59.000Z" },
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 } },
  {
   "title": "⚠️Alarm!",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT status, date_time FROM smart_home.alarm "
    }
   ]
  },
  {
   "title": "⚠️Motion Detection!",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT motion_status, date_time FROM smart_home.motion_sensor"
    }
   ]
  },
  {
   "title": "Live Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_average, date_time FROM smart_home.temperature_sensor "
    }
   ]
  },
  {
   "title": "🌡️Average Temperature, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_average, date_time FROM smart_home.temperature_sensor "
    }
   ]
  },
  {
   "title": "🌡️Sensor Temperature TH1, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temperature\nFROM temperature_sensor\nWHERE\n  $__timeFilter(date_time) AND\n  name = 'TH1'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "🌡️Temperature TH2, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temperature\nFROM temperature_sensor\nWHERE\n  $__timeFilter(date_time) AND\n  name = \"TH2\"\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "🌡️Temperature Difference, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT temperature_diff, date_time FROM smart_home.temperature_sensor "
    }
   ]
  },
  {
   "title": "⚡Total Energy, 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  total_energy\nFROM total_energy_sensor\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "⚡Max Total Energy, 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  sensor_max\nFROM total_energy_sensor\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "🌊 Total Water Consumption, 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT total_consumption, date_time FROM smart_home.total_water_consumption_sensor "
    }
   ]
  },
  {
   "title": "🌊 Max Total Water Consumption, 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_max, date_time FROM smart_home.total_water_consumption_sensor "
    }
   ]
  },
  {
   "title": "🔌Electric Device Energy Sum, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_sum, date_time FROM smart_home.electric_device_energy_sensor "
    }
   ]
  },
  {
   "title": "🔌MiAC1, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT energy, date_time, name FROM smart_home.electric_device_energy_sensor WHERE name='MiAC1'"
    }
   ]
  },
  {
   "title": "🔌MiAC2, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT energy, date_time, name FROM smart_home.electric_device_energy_sensor WHERE name='MiAC2'"
    }
   ]
  },
  {
   "title": "🌬️Air Condition Sensor Sum, 15' ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  sensor_sum\nFROM air_condition_energy_sensor\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time\n"
    }
   ]
  },
  {
   "title": "🌬️HVAC1, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT energy, date_time FROM smart_home.air_condition_energy_sensor WHERE name='HVAC1' "
    }
   ]
  },
  {
   "title": "🌬️HVAC2, 15'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT energy, date_time FROM smart_home.air_condition_energy_sensor WHERE name='HVAC2' "
    }
   ]
  },
  {
   "title": "🚿 Water Consumption Sum, 15'",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_sum, date_time FROM smart_home.water_consumption_sensor"
    }
   ]
  },
  {
   "title": "🚿 Water Consumption Sensor W1, 15'",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT consumption, date_time FROM smart_home.water_consumption_sensor WHERE name='W1' "
    }
   ]
  },
  {
   "title": "🚿 Water Consumption Sensor W2 (to be installed), 15'",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT consumption, date_time FROM smart_home.water_consumption_sensor WHERE name='W2' "
    }
   ]
  },
  {
   "title": "❌Late Rejected Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "dataset": "smart_home",
     "rawSql": "SELECT sensor_name, device_status, measurement, event_id, description, date_time FROM smart_home.late_rejected_event LIMIT 50 "
    }
   ]
  },
  {
   "title": "API Call test",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  id\nFROM air_condition_energy_sensor\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Future Work: Multiple Smart House Monitoring",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 82 },
   "valueName": "total"
  }
 ]
}